### ISSUE TITLE
mg812

### ISSUE THREAD

**Issue by thgebull** [yngyu/log_room_environment#1]
Dear kollegue,
Could me get a more informations about sensor mg812, how you close issuse During aging, in order to keep the power on at all times, we applied DC5V using a separate adapter and left it near a window near the outside atmosphere. At the start of aging, the output voltage was unstable and started at around 1V.

**Comment by yngyu** [comment]
I used [this datasheet](https://akizukidenshi.com/download/ds/winsen/mg812.pdf) as the reference of calculation.
Actually, as you mentioned, the beginning of it's aging is pretty unstable and not accurate, so I ignored that period.
